# Generated by Django 4.2.4 on 2024-02-26 02:52

from django.db import migrations, models
import django.db.models.deletion
import formularios.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sitio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("PTICellID", models.CharField(max_length=100)),
                ("EntelID", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Formulario1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lat",
                    models.FloatField(
                        validators=[formularios.validators.validar_latitud]
                    ),
                ),
                (
                    "lon",
                    models.FloatField(
                        validators=[formularios.validators.validar_longitud]
                    ),
                ),
                (
                    "sitio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="formularios.sitio",
                    ),
                ),
            ],
        ),
    ]
