# Generated by Django 5.0.2 on 2024-02-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formularios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulario1",
            name="entel_id",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
