# Generated by Django 5.0.2 on 2024-02-29 14:20

import django.db.models.deletion
import formularios.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formularios", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="formulario1",
            name="accesoSitio",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="formulario1",
            name="accesoSitioConstruccion",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="formulario1",
            name="adicionales",
            field=models.TextField(default="Sin adicionales"),
        ),
        migrations.AddField(
            model_name="formulario1",
            name="capacidadEnergia",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="formulario1",
            name="comuna",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="formulario1",
            name="deslindes",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="formulario1",
            name="dimensiones",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="formulario1",
            name="distanciaEmpalmeSitio",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="formulario1",
            name="entel_id",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="formulario1",
            name="latEnergia",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[formularios.validators.validar_latitud],
            ),
        ),
        migrations.AddField(
            model_name="formulario1",
            name="lonEnergia",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[formularios.validators.validar_longitud],
            ),
        ),
        migrations.AddField(
            model_name="formulario1",
            name="longitudAcceso",
            field=models.IntegerField(
                null=True, validators=[formularios.validators.validar_longitud_sitio]
            ),
        ),
        migrations.AddField(
            model_name="formulario1",
            name="longitudAccesoConstuccion",
            field=models.IntegerField(
                null=True, validators=[formularios.validators.validar_longitud]
            ),
        ),
        migrations.AddField(
            model_name="formulario1",
            name="nombre",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="formulario1",
            name="obstaculos",
            field=models.TextField(default="Sin obstaculos"),
        ),
        migrations.AddField(
            model_name="formulario1",
            name="proveedorEnergia",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="formulario1",
            name="provincia",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="formulario1",
            name="tipoSuelo",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="formulario1",
            name="usuario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="formularios",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sitio",
            name="Comuna",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="sitio",
            name="Nombre",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="sitio",
            name="Provincia",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="sitio",
            name="lat_inmobiliaria",
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="sitio",
            name="lat_mandato",
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="sitio",
            name="lat_nominal",
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="sitio",
            name="lon_inmobiliaria",
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="sitio",
            name="lon_mandato",
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="sitio",
            name="lon_nominal",
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
    ]
