# Generated by Django 5.0.2 on 2024-02-26 03:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("formularios", "0002_formulario1_entel_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formulario1",
            name="entel_id",
        ),
    ]
