# Generated by Django 5.0.2 on 2024-02-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formularios", "0004_formulario1_entel_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitio",
            name="comuna",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="sitio",
            name="nombre",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="sitio",
            name="provincia",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
