# Generated by Django 5.0.2 on 2024-02-26 14:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("formularios", "0005_sitio_comuna_sitio_nombre_sitio_provincia"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sitio",
            old_name="comuna",
            new_name="Comuna",
        ),
        migrations.RenameField(
            model_name="sitio",
            old_name="nombre",
            new_name="Nombre",
        ),
        migrations.RenameField(
            model_name="sitio",
            old_name="provincia",
            new_name="Provincia",
        ),
    ]
