# Generated by Django 5.0.2 on 2024-02-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formularios", "0006_rename_comuna_sitio_comuna_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulario1",
            name="comuna",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="formulario1",
            name="nombre",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="formulario1",
            name="provincia",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
