# Generated by Django 5.0.2 on 2024-02-29 16:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("formularios", "0006_formulariotx_dist_inmobiliaria_inspeccion_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="formulariotx",
            old_name="latEnergia",
            new_name="lat_energia",
        ),
        migrations.RenameField(
            model_name="formulariotx",
            old_name="lonEnergia",
            new_name="lon_energia",
        ),
    ]
