# Generated by Django 5.0.2 on 2024-02-26 16:41

import formularios.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formularios", "0007_formulario1_comuna_formulario1_nombre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulario1",
            name="accesoSitio",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name="formulario1",
            name="adicionales",
            field=models.TextField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name="formulario1",
            name="capacidadEnergia",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name="formulario1",
            name="deslindes",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="formulario1",
            name="dimensiones",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="formulario1",
            name="distEmpalmeSitio",
            field=models.IntegerField(
                default=100, validators=[formularios.validators.validar_longitud]
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="formulario1",
            name="latEnergia",
            field=models.FloatField(
                default=10, validators=[formularios.validators.validar_latitud]
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="formulario1",
            name="lonEnergia",
            field=models.FloatField(
                default=10, validators=[formularios.validators.validar_longitud]
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="formulario1",
            name="longitudAcceso",
            field=models.IntegerField(
                default=100, validators=[formularios.validators.validar_longitud_sitio]
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="formulario1",
            name="longitudAccesoConstuccion",
            field=models.IntegerField(
                default=100, validators=[formularios.validators.validar_longitud]
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="formulario1",
            name="obstaculos",
            field=models.TextField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name="formulario1",
            name="tipoSuelo",
            field=models.TextField(blank=True, max_length=512),
        ),
    ]
