# Generated by Django 5.0.2 on 2024-02-29 22:14

import django.db.models.deletion
import formularios.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formularios", "0007_rename_latenergia_formulariotx_lat_energia_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulariotx",
            name="usuario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="formularios_tx",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="FormularioPreIng",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entel_id", models.CharField(blank=True, max_length=10)),
                ("nombre", models.CharField(blank=True, max_length=100)),
                ("comuna", models.CharField(blank=True, max_length=20)),
                ("provincia", models.CharField(blank=True, max_length=50)),
                (
                    "lat",
                    models.FloatField(
                        validators=[formularios.validators.validar_latitud]
                    ),
                ),
                (
                    "lon",
                    models.FloatField(
                        validators=[formularios.validators.validar_longitud]
                    ),
                ),
                ("dimensiones", models.CharField(max_length=100, null=True)),
                ("deslindes", models.CharField(max_length=100, null=True)),
                ("accesoSitio", models.TextField(null=True)),
                ("accesoSitioConstruccion", models.TextField(null=True)),
                (
                    "longitudAcceso",
                    models.IntegerField(
                        null=True,
                        validators=[formularios.validators.validar_longitud_sitio],
                    ),
                ),
                (
                    "longitudAccesoConstuccion",
                    models.IntegerField(
                        null=True, validators=[formularios.validators.validar_longitud]
                    ),
                ),
                ("tipoSuelo", models.TextField(null=True)),
                ("obstaculos", models.TextField(default="Sin obstaculos")),
                ("adicionales", models.TextField(default="Sin adicionales")),
                (
                    "proveedorEnergia",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("capacidadEnergia", models.CharField(blank=True, max_length=20)),
                (
                    "lat_energia",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[formularios.validators.validar_latitud],
                    ),
                ),
                (
                    "lon_energia",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[formularios.validators.validar_longitud],
                    ),
                ),
                ("distanciaEmpalmeSitio", models.IntegerField(blank=True, null=True)),
                (
                    "lat_mandato",
                    models.FloatField(blank=True, max_length=10, null=True),
                ),
                (
                    "lon_mandato",
                    models.FloatField(blank=True, max_length=10, null=True),
                ),
                ("dist_mandato_ingenieria", models.IntegerField(blank=True, null=True)),
                (
                    "sitio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="formularios.sitio",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formularios_preing",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Formulario Pre-Ingenieria",
                "verbose_name_plural": "Formularios Pre-Ingenieria",
            },
        ),
    ]
