# Generated by Django 5.0.2 on 2024-02-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formularios", "0008_alter_formulariotx_usuario_formulariopreing"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulariopreing",
            name="comentario",
            field=models.TextField(blank=True, default="Sin comentarios", null=True),
        ),
        migrations.AddField(
            model_name="formulariotx",
            name="comentario",
            field=models.TextField(blank=True, default="Sin comentarios", null=True),
        ),
    ]
