# Generated by Django 5.0.2 on 2024-03-01 17:00

import django.db.models.deletion
import formularios.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formularios", "0009_formulariopreing_comentario_formulariotx_comentario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulariopreing",
            name="accesoSitio",
            field=models.TextField(null=True, verbose_name="Acceso al Sitio"),
        ),
        migrations.AlterField(
            model_name="formulariopreing",
            name="accesoSitioConstruccion",
            field=models.TextField(
                null=True, verbose_name="Acceso al Sitio para Construccion"
            ),
        ),
        migrations.AlterField(
            model_name="formulariopreing",
            name="adicionales",
            field=models.TextField(
                default="Sin adicionales", verbose_name="Trabajos Adicionales"
            ),
        ),
        migrations.AlterField(
            model_name="formulariopreing",
            name="capacidadEnergia",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Capacidad de Energia"
            ),
        ),
        migrations.AlterField(
            model_name="formulariopreing",
            name="dist_mandato_ingenieria",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Distancia de Mandato a Ingeniería"
            ),
        ),
        migrations.AlterField(
            model_name="formulariopreing",
            name="distanciaEmpalmeSitio",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Distancia de Empalme a Sitio"
            ),
        ),
        migrations.AlterField(
            model_name="formulariopreing",
            name="lat",
            field=models.FloatField(
                validators=[formularios.validators.validar_latitud],
                verbose_name="Latitud Inspeccion",
            ),
        ),
        migrations.AlterField(
            model_name="formulariopreing",
            name="lat_energia",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[formularios.validators.validar_latitud],
                verbose_name="Latitud de Empalme",
            ),
        ),
        migrations.AlterField(
            model_name="formulariopreing",
            name="lat_mandato",
            field=models.FloatField(
                blank=True, max_length=10, null=True, verbose_name="Latitud Mandato"
            ),
        ),
        migrations.AlterField(
            model_name="formulariopreing",
            name="lon",
            field=models.FloatField(
                validators=[formularios.validators.validar_longitud],
                verbose_name="Longitud Inspeccion",
            ),
        ),
        migrations.AlterField(
            model_name="formulariopreing",
            name="lon_energia",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[formularios.validators.validar_longitud],
                verbose_name="Longitud de Empalme",
            ),
        ),
        migrations.AlterField(
            model_name="formulariopreing",
            name="lon_mandato",
            field=models.FloatField(
                blank=True, max_length=10, null=True, verbose_name="Longitud Mandato"
            ),
        ),
        migrations.AlterField(
            model_name="formulariopreing",
            name="longitudAcceso",
            field=models.IntegerField(
                null=True,
                validators=[formularios.validators.validar_longitud_sitio],
                verbose_name="Longitud de Acceso",
            ),
        ),
        migrations.AlterField(
            model_name="formulariopreing",
            name="longitudAccesoConstuccion",
            field=models.IntegerField(
                null=True,
                validators=[formularios.validators.validar_longitud],
                verbose_name="Longitud de Acceso para Construccion",
            ),
        ),
        migrations.AlterField(
            model_name="formulariopreing",
            name="proveedorEnergia",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Provvedor de Energía",
            ),
        ),
        migrations.AlterField(
            model_name="formulariopreing",
            name="sitio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="formularios.sitio",
                verbose_name="Sitio Cod PTI",
            ),
        ),
        migrations.AlterField(
            model_name="formulariopreing",
            name="tipoSuelo",
            field=models.TextField(null=True, verbose_name="Tipo de Suelo"),
        ),
        migrations.AlterField(
            model_name="formulariotx",
            name="accesoSitio",
            field=models.TextField(null=True, verbose_name="Acceso al Sitio"),
        ),
        migrations.AlterField(
            model_name="formulariotx",
            name="accesoSitioConstruccion",
            field=models.TextField(
                null=True, verbose_name="Acceso al Sitio para Construccion"
            ),
        ),
        migrations.AlterField(
            model_name="formulariotx",
            name="adicionales",
            field=models.TextField(
                default="Sin adicionales", verbose_name="Trabajos Adicionales"
            ),
        ),
        migrations.AlterField(
            model_name="formulariotx",
            name="capacidadEnergia",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Capacidad de Energia"
            ),
        ),
        migrations.AlterField(
            model_name="formulariotx",
            name="dist_inmobiliaria_inspeccion",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Distancia Inmobiliaria a Inspeccio"
            ),
        ),
        migrations.AlterField(
            model_name="formulariotx",
            name="dist_nominal_inmobiliaria",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Distancia Nominal a Inmobiliaria"
            ),
        ),
        migrations.AlterField(
            model_name="formulariotx",
            name="dist_nominal_inspeccion",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Distancia Nominal a Inspeccion"
            ),
        ),
        migrations.AlterField(
            model_name="formulariotx",
            name="distanciaEmpalmeSitio",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Distancia entre Empalme y Sitio"
            ),
        ),
        migrations.AlterField(
            model_name="formulariotx",
            name="lat",
            field=models.FloatField(
                validators=[formularios.validators.validar_latitud],
                verbose_name="Latitud Inspeccion",
            ),
        ),
        migrations.AlterField(
            model_name="formulariotx",
            name="lat_energia",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[formularios.validators.validar_latitud],
                verbose_name="Latitud de Empalme",
            ),
        ),
        migrations.AlterField(
            model_name="formulariotx",
            name="lat_inmobiliaria",
            field=models.FloatField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Latitud Inmobiliaria",
            ),
        ),
        migrations.AlterField(
            model_name="formulariotx",
            name="lat_nominal",
            field=models.FloatField(
                blank=True, max_length=10, null=True, verbose_name="Latitud Nominal"
            ),
        ),
        migrations.AlterField(
            model_name="formulariotx",
            name="lon",
            field=models.FloatField(
                validators=[formularios.validators.validar_longitud],
                verbose_name="Longitud Inspeccion",
            ),
        ),
        migrations.AlterField(
            model_name="formulariotx",
            name="lon_energia",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[formularios.validators.validar_longitud],
                verbose_name="Longitud de Empalme",
            ),
        ),
        migrations.AlterField(
            model_name="formulariotx",
            name="lon_inmobiliaria",
            field=models.FloatField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Longitud Inmobiliaria",
            ),
        ),
        migrations.AlterField(
            model_name="formulariotx",
            name="lon_nominal",
            field=models.FloatField(
                blank=True, max_length=10, null=True, verbose_name="Longitud Nominal"
            ),
        ),
        migrations.AlterField(
            model_name="formulariotx",
            name="longitudAcceso",
            field=models.IntegerField(
                null=True,
                validators=[formularios.validators.validar_longitud_sitio],
                verbose_name="Longitud de Acceso",
            ),
        ),
        migrations.AlterField(
            model_name="formulariotx",
            name="longitudAccesoConstuccion",
            field=models.IntegerField(
                null=True,
                validators=[formularios.validators.validar_longitud],
                verbose_name="Longitud de Acceso para Construccion",
            ),
        ),
        migrations.AlterField(
            model_name="formulariotx",
            name="proveedorEnergia",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Provvedor de Energía",
            ),
        ),
        migrations.AlterField(
            model_name="formulariotx",
            name="sitio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="formularios.sitio",
                verbose_name="Sitio Cod PTI",
            ),
        ),
    ]
