# Generated by Django 5.0.2 on 2024-02-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formularios", "0009_remove_formulario1_accesositio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulario1",
            name="dimensiones",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
