# Generated by Django 5.0.2 on 2024-03-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formularios", "0010_alter_formulariopreing_accesositio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulariopreing",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="imagenes_mapas/"),
        ),
    ]
