# Generated by Django 5.0.2 on 2024-02-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formularios", "0010_formulario1_dimensiones"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulario1",
            name="deslindes",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
