# Generated by Django 5.0.2 on 2024-03-01 21:48

import formularios.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formularios", "0011_formulariopreing_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulariopreing",
            name="dist_mandato_ingenieria",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Distancia Inspeccion Mandato/Inmobiliaria (m)",
            ),
        ),
        migrations.AlterField(
            model_name="formulariopreing",
            name="distanciaEmpalmeSitio",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Distancia de Empalme a Sitio (m)"
            ),
        ),
        migrations.AlterField(
            model_name="formulariopreing",
            name="lat_mandato",
            field=models.FloatField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Latitud Mandato/Inmobiliaria",
            ),
        ),
        migrations.AlterField(
            model_name="formulariopreing",
            name="lon_mandato",
            field=models.FloatField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Longitud Mandato/Inmobiliaria",
            ),
        ),
        migrations.AlterField(
            model_name="formulariopreing",
            name="longitudAcceso",
            field=models.IntegerField(
                null=True,
                validators=[formularios.validators.validar_longitud_sitio],
                verbose_name="Longitud de Acceso (m)",
            ),
        ),
        migrations.AlterField(
            model_name="formulariopreing",
            name="longitudAccesoConstuccion",
            field=models.IntegerField(
                null=True,
                validators=[formularios.validators.validar_longitud],
                verbose_name="Longitud de Acceso para Construccion (m)",
            ),
        ),
        migrations.AlterField(
            model_name="formulariopreing",
            name="proveedorEnergia",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Proveedor de Energía",
            ),
        ),
    ]
