# Generated by Django 5.0.2 on 2024-02-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formularios", "0011_formulario1_deslindes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulario1",
            name="deslindes",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="formulario1",
            name="dimensiones",
            field=models.CharField(max_length=100),
        ),
    ]
