# Generated by Django 5.0.2 on 2024-02-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formularios", "0012_alter_formulario1_deslindes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulario1",
            name="accesoSitio",
            field=models.CharField(default=2, max_length=256),
            preserve_default=False,
        ),
    ]
