# Generated by Django 5.0.2 on 2024-02-26 22:06

import formularios.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formularios", "0013_formulario1_accesositio"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulario1",
            name="longitudAcceso",
            field=models.IntegerField(
                default=12, validators=[formularios.validators.validar_longitud_sitio]
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="formulario1",
            name="longitudAccesoConstuccion",
            field=models.IntegerField(
                default=12, validators=[formularios.validators.validar_longitud]
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="formulario1",
            name="accesoSitio",
            field=models.TextField(max_length=256),
        ),
    ]
