# Generated by Django 5.0.2 on 2024-03-01 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formularios", "0013_formulariopreing_imagen_deslindes"),
        ("main", "0003_alter_image_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulariopreing",
            name="imagen_deslindes",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.image",
            ),
        ),
    ]
