# Generated by Django 5.0.2 on 2024-02-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formularios", "0014_formulario1_longitudacceso_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulario1",
            name="accesoSitioConstruccion",
            field=models.TextField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="formulario1",
            name="tipoSuelo",
            field=models.TextField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="formulario1",
            name="accesoSitio",
            field=models.TextField(),
        ),
    ]
