# Generated by Django 5.0.2 on 2024-02-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formularios", "0015_formulario1_accesositioconstruccion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulario1",
            name="adicionales",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="formulario1",
            name="obstaculos",
            field=models.TextField(default="Sin obstaculos"),
        ),
    ]
