# Generated by Django 5.0.2 on 2024-02-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formularios", "0016_formulario1_adicionales_formulario1_obstaculos"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulario1",
            name="proveedorEnergia",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
