# Generated by Django 5.0.2 on 2024-03-01 23:25

import formularios.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formularios", "0016_remove_formulariopreing_imagen_deslindes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formulariotx",
            name="dist_nominal_inmobiliaria",
        ),
        migrations.RemoveField(
            model_name="formulariotx",
            name="dist_nominal_inspeccion",
        ),
        migrations.RemoveField(
            model_name="formulariotx",
            name="lat_nominal",
        ),
        migrations.RemoveField(
            model_name="formulariotx",
            name="lon_nominal",
        ),
        migrations.RemoveField(
            model_name="sitio",
            name="lat_nominal",
        ),
        migrations.RemoveField(
            model_name="sitio",
            name="lon_nominal",
        ),
        migrations.AddField(
            model_name="formulariotx",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="imagenes_mapas/"),
        ),
        migrations.AlterField(
            model_name="formulariotx",
            name="dist_inmobiliaria_inspeccion",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Distancia Inmobiliaria a Inspeccion (m)",
            ),
        ),
        migrations.AlterField(
            model_name="formulariotx",
            name="distanciaEmpalmeSitio",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Distancia de Empalme a Sitio (m)"
            ),
        ),
        migrations.AlterField(
            model_name="formulariotx",
            name="longitudAcceso",
            field=models.IntegerField(
                null=True,
                validators=[formularios.validators.validar_longitud_sitio],
                verbose_name="Longitud de Acceso (m)",
            ),
        ),
        migrations.AlterField(
            model_name="formulariotx",
            name="longitudAccesoConstuccion",
            field=models.IntegerField(
                null=True,
                validators=[formularios.validators.validar_longitud],
                verbose_name="ongitud de Acceso para Construccion (m)",
            ),
        ),
        migrations.AlterField(
            model_name="formulariotx",
            name="proveedorEnergia",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Proveedor de Energía",
            ),
        ),
        migrations.AlterField(
            model_name="formulariotx",
            name="tipoSuelo",
            field=models.TextField(null=True, verbose_name="Tipo de Suelo"),
        ),
    ]
