# Generated by Django 5.0.2 on 2024-02-26 23:05

import formularios.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formularios", "0017_formulario1_proveedorenergia"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulario1",
            name="latEnergia",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[formularios.validators.validar_latitud],
            ),
        ),
        migrations.AddField(
            model_name="formulario1",
            name="lonEnergia",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[formularios.validators.validar_longitud],
            ),
        ),
    ]
