# Generated by Django 5.0.2 on 2024-02-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formularios", "0018_formulario1_latenergia_formulario1_lonenergia"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulario1",
            name="capacidadEnergia",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="formulario1",
            name="distanciaEmpalmeSitio",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
