# Generated by Django 5.0.2 on 2024-02-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formularios", "0019_formulario1_capacidadenergia_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulario1",
            name="distanciaEmpalmeSitio",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
