# Generated by Django 5.0.2 on 2024-03-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formularios", "0021_formulariopreing_altura_formulariotx_altura_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitio",
            name="lat_mandato",
            field=models.FloatField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Latitud Mandato/Inmobiliaria",
            ),
        ),
        migrations.AlterField(
            model_name="sitio",
            name="lon_mandato",
            field=models.FloatField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Longitud Mandato/Inmobiliaria",
            ),
        ),
    ]
