# Generated by Django 5.0.2 on 2024-03-02 14:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formularios", "0022_alter_sitio_lat_mandato_alter_sitio_lon_mandato"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulariopreing",
            name="fecha_creacion",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="formulariotx",
            name="fecha_creacion",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
