# Generated by Django 5.0.2 on 2024-03-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formularios", "0023_formulariopreing_fecha_creacion_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitio",
            name="lat_inmobiliaria",
        ),
        migrations.RemoveField(
            model_name="sitio",
            name="lat_mandato",
        ),
        migrations.RemoveField(
            model_name="sitio",
            name="lon_inmobiliaria",
        ),
        migrations.RemoveField(
            model_name="sitio",
            name="lon_mandato",
        ),
        migrations.AlterField(
            model_name="formulariopreing",
            name="lat_mandato",
            field=models.FloatField(
                blank=True, max_length=10, null=True, verbose_name="Latitud Mandato"
            ),
        ),
        migrations.AlterField(
            model_name="formulariopreing",
            name="lon_mandato",
            field=models.FloatField(
                blank=True, max_length=10, null=True, verbose_name="Longitud Mandato"
            ),
        ),
    ]
