# Generated by Django 5.0.2 on 2024-03-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formularios", "0024_remove_sitio_lat_inmobiliaria_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formulariotx",
            name="dist_inmobiliaria_inspeccion",
        ),
        migrations.RemoveField(
            model_name="formulariotx",
            name="lat_inmobiliaria",
        ),
        migrations.RemoveField(
            model_name="formulariotx",
            name="lon_inmobiliaria",
        ),
        migrations.AddField(
            model_name="formulariotx",
            name="dist_base_inspeccion",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Distancia Inmobiliaria/Mandato a Inspeccion (m)",
            ),
        ),
        migrations.AddField(
            model_name="formulariotx",
            name="lat_base",
            field=models.FloatField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Latitud Inmobiliaria/Mandato",
            ),
        ),
        migrations.AddField(
            model_name="formulariotx",
            name="lon_base",
            field=models.FloatField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Longitud Inmobiliaria/Mandato",
            ),
        ),
        migrations.DeleteModel(
            name="FormularioPreIng",
        ),
    ]
