# Generated by Django 5.0.2 on 2024-03-03 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formularios", "0026_alter_formulariotx_options_formulariotx_etapa"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulariotx",
            name="altura",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="formulariotx",
            name="usuario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="formularios_1",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
