# Generated by Django 5.0.2 on 2024-03-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "formularios",
            "0030_remove_image_description_remove_image_main_model_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.FileField(upload_to="attachments"),
        ),
    ]
