# Generated by Django 5.0.2 on 2024-03-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formularios", "0033_delete_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitio",
            name="lat_base",
            field=models.FloatField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Latitud Inmobiliaria/Mandato",
            ),
        ),
        migrations.AddField(
            model_name="sitio",
            name="lon_base",
            field=models.FloatField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Longitud Inmobiliaria/Mandato",
            ),
        ),
        migrations.AlterField(
            model_name="formulariotx",
            name="altura",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Altura (m)"
            ),
        ),
        migrations.AlterField(
            model_name="formulariotx",
            name="dist_base_inspeccion",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Desfase de Ubicación (m)"
            ),
        ),
    ]
