# Generated by Django 5.0.2 on 2024-03-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formularios", "0034_sitio_lat_base_sitio_lon_base_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitio",
            name="altura",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
