# Generated by Django 5.0.2 on 2024-03-06 19:06

import formularios.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formularios", "0035_alter_sitio_altura"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitio",
            name="lat_base",
        ),
        migrations.RemoveField(
            model_name="sitio",
            name="lon_base",
        ),
        migrations.AlterField(
            model_name="formulariotx",
            name="dist_base_inspeccion",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Desfase (m)"
            ),
        ),
        migrations.AlterField(
            model_name="formulariotx",
            name="longitudAccesoConstuccion",
            field=models.IntegerField(
                null=True,
                validators=[formularios.validators.validar_longitud_sitio],
                verbose_name="Longitud Acceso Construccion (m)",
            ),
        ),
    ]
