# Generated by Django 5.0.2 on 2024-03-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="title",
            field=models.CharField(default="deslindas", max_length=255),
        ),
    ]
