# Generated by Django 5.0.2 on 2024-03-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_image_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="title",
            field=models.CharField(default="deslindes", max_length=255),
        ),
    ]
