# Generated by Django 5.0.2 on 2024-03-04 02:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_image_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={
                "verbose_name": "Imagen Deslindes",
                "verbose_name_plural": "Imagen Deslindes",
            },
        ),
    ]
