# Generated by Django 5.0.2 on 2024-03-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Imagen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("imagen", models.ImageField(upload_to="imagenes/")),
                ("descripcion", models.TextField(blank=True)),
            ],
        ),
    ]
