# Generated by Django 5.0.2 on 2024-03-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imagenes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imagen",
            name="descripcion",
        ),
        migrations.RemoveField(
            model_name="imagen",
            name="titulo",
        ),
        migrations.AlterField(
            model_name="imagen",
            name="imagen",
            field=models.FileField(upload_to="fotografias/"),
        ),
    ]
