# Generated by Django 5.0.2 on 2024-03-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imagenes", "0002_remove_imagen_descripcion_remove_imagen_titulo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="attachments")),
            ],
        ),
        migrations.DeleteModel(
            name="Imagen",
        ),
    ]
