# Generated by Django 5.0.2 on 2024-03-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imagenes", "0003_attachment_delete_imagen"),
    ]

    operations = [
        migrations.CreateModel(
            name="Imagen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("imagen", models.ImageField(upload_to="fotografias/")),
                ("cargado_en", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Attachment",
        ),
    ]
