# Generated by Django 5.0.2 on 2024-03-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imagenes", "0004_imagen_delete_attachment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pic", models.FileField(upload_to="fotografias/")),
            ],
        ),
        migrations.DeleteModel(
            name="Imagen",
        ),
    ]
