# Generated by Django 5.0.2 on 2024-03-03 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formularios", "0033_delete_attachment"),
        ("imagenes", "0007_remove_image_sitio"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="sitio",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="formularios.sitio",
                verbose_name="Sitio asociado",
            ),
        ),
    ]
