# Generated by Django 5.0.2 on 2024-03-04 02:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("imagenes", "0013_alter_image_sitio"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Image",
        ),
    ]
