# Generated by Django 5.0.2 on 2024-03-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imagenes", "0015_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="sitio",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
