# Generated by Django 5.0.2 on 2024-03-04 02:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imagenes", "0017_formulariotx_image_etapa"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
    ]
